### ISSUE TITLE
documentation for getting device ID doesn't seem to be correct

### ISSUE THREAD

**Issue by cloudkucooland** [redgoose/daikin-one#1]
scot@covert:/home/scot/daikin-one % ./daikin-one device ls
Error: required flag(s) "device-id" not set
Usage:
  daikin-one device ls [flags]

Flags:
  -h, --help   help for ls

Global Flags:
  -c, --config string      config file (default "/home/scot/.daikin/daikin.yaml")
      --db string          Local path to SQLite database (default "/home/scot/.daikin/daikin.db")
  -d, --device-id string   Daikin device ID

required flag(s) "device-id" not set

**Comment by redgoose** [comment]
Thanks for opening an issue, fixed now:
https://github.com/redgoose/daikin-one/commit/9c164ddc952973d4a679cc3d4f6456405d1d6e96

**Comment by redgoose** [comment]
thanks for opening an issue, fixed now.
run the following again to pull the latest version:

`go install github.com/redgoose/daikin-one@latest`

**Comment by cloudkucooland** [comment]
It is working for me now. Thanks!
