### ISSUE TITLE
Current API is limited

### ISSUE THREAD

**Issue by redgoose** [redgoose/daikin-one#5]
Current API being used is limited in what it returns and what changes it can perform. 

@cloudkucooland heads up that I will be replacing daikin.go at some point with a new package (and new underlying API) that will have a new interface and new features that are currently not possible

**Comment by cloudkucooland** [comment]
OK, I'll wait for your work.

my work-to-date is available here: https://github.com/cloudkucooland/daikin-one/blob/main/daikin/daikin.go

**Comment by redgoose** [comment]
@cloudkucooland so my idea was to inspect and attempt to replicate what the mobile app does. You can see my work so far here: https://github.com/redgoose/daikin-skyport . I incorporated the changes you made above and also took your advice and separated it out into it's own repo.

Cool thing about this library is the sheer amount of [device info available](https://pkg.go.dev/github.com/redgoose/daikin-skyport#DeviceInfo). 

You can do a bunch of undocumented things like change the mininum setpoint delta or the lightbar brightness of your thermostat which aren't even possible with the mobile app.

I later found this [python library](https://github.com/apetrycki/daikinskyport/blob/master/custom_components/daikinskyport/daikinskyport.py) which is using the same api. I'll probably incorporate the sensor stuff it's doing.

Not sure if you came across it, but I also found a way to overcome the [running status limitation](https://github.com/redgoose/daikin-one#limitations) with the existing api, but that's still in the works as I first have to switch this project over to using this new library.

Let me know your thoughts and what you're up to.

**Comment by cloudkucooland** [comment]
Very cool, thanks for all your work on this. I will switch my code over to it this afternoon and start to see what it can do.

It looks like I'm going to be able to export a lot more values to my home monitoring system. 

Let me know if there is anything you need that would be helpful other than testing.

**Comment by cloudkucooland** [comment]
I've upgraded my HomeKit bridge, my work is here: https://github.com/cloudkucooland/HomeKitBridges/blob/main/DaikinOneHKBridge/device.go

**Comment by redgoose** [comment]
switched to using daikin skyport api: https://github.com/redgoose/daikin-one/commit/87e2c0ea76b4723b275a88d0523064b7a70d5617
