### ISSUE TITLE
Report temperature conversion appears wrong

### ISSUE THREAD

**Issue by zkendall** [redgoose/daikin-one#8]
I set F in my config, and F is used as label in chart, but the values appear to be C values.
<img width="716" alt="image" src="https://github.com/redgoose/daikin-one/assets/2762875/3200369a-77bc-4ae2-938f-b394c6469fb0">

**Comment by redgoose** [comment]
I have my thermostat set to C and use C in my config with no issues.I am away from home at the moment so can’t test it with F. What unit is displayed on your thermostat?What temperature units get returned when you run step 5 of the Quick Start in the readme? (ie. tempOutdoor, cspHome, etc)On Feb 18, 2024, at 3:54 PM, Zack Kendall ***@***.***> wrote:﻿
I set F in my config, and F is used as label in chart, but the values appear to be C values.
image.png (view on web)

**Comment by redgoose** [comment]
I have my thermostat set to C and use C in my config with no issues.

I am away from home at the moment so can’t test it with F.

What unit is displayed on your thermostat?

What temperature units get returned when you run step 5 of the Quick Start in the readme? (ie. tempOutdoor, cspHome, etc)

**Comment by zkendall** [comment]
My thermostat is set to F, but I still get C from the API (deviceInfo). For example, I get `"tempIndoor": 18.6,` when my thermostat says 65F.

So I think the right thing to do is keep logging the data to the db as it does now. But when generating the report do a conversion if necessary. I'm going to take a stab at this now.

**Comment by zkendall** [comment]
Addressed here: https://github.com/redgoose/daikin-one/pull/9

**Comment by redgoose** [comment]
why do you want to keep it logging as C and do a temperature conversion every time you read from the db? wouldn't logging as F be more useful?

**Comment by redgoose** [comment]
thanks for your contribution!
